# Generated by Django 6.0 on 2025-12-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('MOBILE', 'Mobile Money'), ('OTHER', 'Other')], default='BANK', max_length=10)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.cycle')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_contributions', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.member')),
            ],
            options={
                'unique_together': {('member', 'cycle')},
            },
        ),
    ]
