# Generated by Django 6.0 on 2025-12-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('digital_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='groups.digitalbook')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('digital_book', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('MOBILE', 'Mobile Money'), ('OTHER', 'Other')], default='BANK', max_length=10)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.cycle')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_contributions', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.member')),
            ],
            options={
                'unique_together': {('member', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('row_number', models.PositiveIntegerField(help_text='Transaction row number on the page')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_entries', to='groups.member')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contributions.page')),
            ],
            options={
                'ordering': ['date', 'row_number'],
                'unique_together': {('page', 'row_number')},
            },
        ),
    ]
