# Generated by Django 5.2.8 on 2025-12-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('groups', '0003_digitalbook_alter_cycle_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('digital_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='groups.digitalbook')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('digital_book', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('row_number', models.PositiveIntegerField(help_text='Transaction row number on the page')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_entries', to='groups.member')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contributions.page')),
            ],
            options={
                'ordering': ['date', 'row_number'],
                'unique_together': {('page', 'row_number')},
            },
        ),
    ]
