# Generated by Django 6.0 on 2025-12-23 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.PositiveIntegerField(default=1, help_text='The sequential number for this ledger book.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('regular', 'Regular Savings'), ('rotating', 'Rotating Fund'), ('investment', 'Investment Group')], default='rotating', max_length=20)),
                ('fixed_deposit_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='The fixed amount each member contributes per cycle.', max_digits=10)),
                ('max_members', models.PositiveIntegerField(default=50, help_text='Maximum number of members allowed in this group')),
                ('cycle_duration_days', models.PositiveIntegerField(default=30, help_text='Duration of each cycle in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(blank=True, help_text='The developer/partner who created this group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to='groups.developer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(help_text='The sequential number of this cycle (e.g., 1, 2, 3...)')),
                ('pot_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount collected in this cycle', max_digits=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='groups.group')),
            ],
            options={
                'ordering': ['group', 'cycle_number'],
                'unique_together': {('group', 'cycle_number')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, editable=False, max_length=10)),
                ('full_name', models.CharField(help_text='The full name of the member.', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('GRADUATED', 'Graduated')], default='PENDING', max_length=10)),
                ('payout_order', models.PositiveIntegerField(blank=True, help_text='The sequence number for receiving the pot in the group.', null=True)),
                ('current_cycle_position', models.PositiveIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_contribution_date', models.DateField(blank=True, null=True)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('digital_book', models.OneToOneField(blank=True, help_text='Digital ledger book assigned to this member', null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.digitalbook')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.OneToOneField(blank=True, help_text='Linked Django user account for login', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payout_order', 'joined_at'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_payouts', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='groups.cycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='groups.member')),
            ],
            options={
                'ordering': ['-payout_date'],
            },
        ),
    ]
