# Generated by Django 6.0 on 2025-12-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='member',
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='digitalbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['page', 'row_number']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='groups_entr_member__fd9d0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='groups_entr_date_f86bfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='groups_entr_status_8a4dee_idx',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cycle',
            name='cycle_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='pot_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active')], default='PLANNED', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(default='APPROVED', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='cycle_duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to='groups.developer'),
        ),
        migrations.AlterField(
            model_name='group',
            name='fixed_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_members',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_book',
            field=models.ForeignKey(blank=True, help_text="Member's current active digital book", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_member', to='groups.digitalbook'),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_contributions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total contributions made by this member', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_payouts',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total payouts received by this member', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='verified_by',
        ),
    ]
