# Generated by Django 6.0 on 2025-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_member_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalbook',
            name='book_number',
            field=models.PositiveIntegerField(default=1, help_text='The sequential number for this ledger book.'),
        ),
    ]
